### ISSUE TITLE
Timelines

### ISSUE THREAD

**Issue by JEGardner** [onfido/onfido-sdk-react-native-sample-app#1]
Hey, we're in the process of making a react native app, which uses onfido. We don't currently have any in-house Java/Swift knowledge so this project will be incredibly helpful. I know it's a cheeky question to ask, but do you have any estimates for when this will be complete? Thanks!

**Comment by seewah** [comment]
Hi our team is actually looking to formalise React Native support over the next few weeks, with extra documentation and sample. We will share our progress with you to get feedback while we are building that out.

**Comment by mikejong0815** [comment]
Hi,
I really appreciate this project and your team's effort on this.
Right now, I need to integrate this to React Native iOS Application, but I don't have any experience with Swift and Objective-C.
So can you help me out to integrate Onfido ios sdk to my projects?

Thanks.

**Comment by anuragajwani** [comment]
Hi @mikejong0815 & @JEGardner,

We have a sample app to showcase integration with the iOS SDK in a branch https://github.com/onfido/onfido-sdk-react-native-sample-app/tree/ios-sdk-integration. Currently it is missing callbacks.

Please note that you have to follow the instructions under `Building Projects with Native Code` tab in https://facebook.github.io/react-native/docs/getting-started.html.

More on integrating with native modules can be found [here](https://facebook.github.io/react-native/docs/native-modules-ios.html) and in order to develop the bridge code between React Native and ObjC you will be required to use Xcode and linking the react native libraries to xcode proj, you can more info [here](https://facebook.github.io/react-native/docs/linking-libraries-ios.html).

[See diff](https://github.com/onfido/onfido-sdk-react-native-sample-app/pull/3/files) for changes when integrating with ios native modules via cocoapods.

I hope this helps,
Anurag

**Comment by isnotahippy** [comment]
My ios knowledge is lacking but I thought I'd try get this running before digging into it properly. Seem to be hitting an incompatibility in dependencies, all I see in the Podfile is the onFido pod though so I wonder if you're aware of this already?

```error: The following binaries use incompatible versions of Swift:
/Users/graememaciver/Library/Developer/Xcode/DerivedData/ReactNativeSampleApp-alidsejfzvavggbjvvdwzajefqfc/Build/Products/Debug-iphoneos/ReactNativeSampleApp.app/Frameworks/Onfido.framework/Onfido
/Users/graememaciver/Library/Developer/Xcode/DerivedData/ReactNativeSampleApp-alidsejfzvavggbjvvdwzajefqfc/Build/Products/Debug-iphoneos/ReactNativeSampleApp.app/Frameworks/SwiftyJSON.framework/SwiftyJSON```
