### ISSUE TITLE
Live Video

### ISSUE THREAD

**Issue by cihanbas** [onfido/onfido-sdk-react-native-sample-app#14]
Hi is supported Live video ?
if you say yes , can you share an example pls 
Thank you

**Comment by sergiomarqmoura** [comment]
Hi @cihanbas 
Please refer to our native [Android](https://github.com/onfido/onfido-android-sdk#face-capture-step) and [iOS](https://github.com/onfido/onfido-ios-sdk#flow-customisation) documentation in order to get instructions to get the live video variant, since this sample app uses the same APIs
